### ISSUE TITLE
大佬你好，请问一直提示无法连接价格查询网站或连接速度过慢该怎么解决？用不用魔法都不行

### ISSUE THREAD

**Issue by KellySakura** [GHMesLing/Paissa#14]

**Comment by NagaResst** [comment]
上周六也收到过相同的反馈，找用户看了一下是电信的问题，拦截了IPv4地址的访问，他把网线插上之后，获得了IPv6的地址。就可以访问了。仅供参考。  
主要还是跟你能不能用浏览器打开 https://universalis.app 有关。如果你用浏览器能打开，用猴面雀却不能查询数据的话，把Data目录里的Paissa.log发给我。

**Comment by KellySakura** [comment]
> 上周六也收到过相同的反馈，找用户看了一下是电信的问题，拦截了IPv4地址的访问，他把网线插上之后，获得了IPv6的地址。就可以访问了。仅供参考。 主要还是跟你能不能用浏览器打开 https://universalis.app 有关。如果你用浏览器能打开，用猴面雀却不能查询数据的话，把Data目录里的Paissa.log发给我。

universalis裸连的话好像登不上，得挂魔法，但是挂魔法，您的软件点搜索就立马显示无法连接网络，因为看您没上传6.3的版本，所以我是将master文件夹下最新的文件都覆盖您4月上传的0.94版中，不知道这个方法对不对
[Paissa.log](https://github.com/NagaResst/Paissa/files/11528284/Paissa.log)

**Comment by NagaResst** [comment]
我也不知道你这么更新会产生什么后果，稍后我会放出最新的0.10.0版本在release里。另外上面发的日志你在挂了梯子的情况下跑出来的吗？

**Comment by KellySakura** [comment]
> 我也不知道你这么更新会产生什么后果，稍后我会放出最新的0.10.0版本在release里。另外上面发的日志你在挂了梯子的情况下跑出来的吗？

好像是的，没挂试了一遍，挂了也试了一遍都不行

**Comment by NagaResst** [comment]
@KellySakura 试试这个 https://github.com/NagaResst/Paissa/releases/download/v1.0.4/Paissa-beta-v1.0.4-for-use-proxy.zip
