### ISSUE TITLE
请问6.3更新后v0.10.0经常打开没反应要怎么排查原因呢

### ISSUE THREAD

**Issue by Dxt777** [GHMesLing/Paissa#15]
工具非常好用 赞美作者 
我遇到的问题是最新版经常双击没反应 重启后正常 过一段时间又双击没反应了 
旧版本的可以正常使用  但替换最新版里的item.pdt后 虽然菜单栏里数据版本显示为6.3 但查询不到6.3的新物品
要怎么排查是什么原因呢

**Comment by NagaResst** [comment]
把Data目录里的Paissa.log发出来看看先， Data目录里还有一个maketable.py ，也需要下载替换才能完全兼容最新版的数据。或者你在菜单栏里点其他，然后把过滤不可再市场上交易的物品选项去掉，就可以查到了。

**Comment by NagaResst** [comment]
我校验了一下在线数据，大概发现是什么问题了，现在开始fix，稍晚点在release里更新版本。

**Comment by Dxt777** [comment]
原来是vpn的原因 开了vpn最新版就打不开 log里也没记录 关掉vpn就正常了
