### ISSUE TITLE
新功能请求：无法在板子出售物品的成本计算

### ISSUE THREAD

**Issue by status102** [GHMesLing/Paissa#3]
比如
1. 收藏品配方
2. 部队工坊配方

现在还没法计算

**Comment by NagaResst** [comment]
不是没法计算，本身功能是支持的。
-----------------------------
但是市场价格查询作为第一展示页，默认就不展示所有无法在市场上出售的物品，所以在查询物品时，直接就过滤掉了 [物品列表过滤](https://github.com/NagaResst/Paissa/blob/1ec52ece06d777fe5570753eaf48789a6a274b92/Queryer.py#L120)
如果不进行物品过滤，使用“水晶”关键词在进行市场查询时，会返回很多诸如：流光水晶一类的任务物品。

发现一个BUG
------
在加入静态资源加速查询之后，没有正确的应用过滤规则。你可以查询到在板子上无法交易的物品，并查询制作成本
在稍后我会修复这个bug，并且在菜单栏添加是否应用过滤的按钮来支持对无法交易物品的查询。

------------------
我印象里部队工房从房子到潜水艇都是可以查询的，而收藏品可以查询对应的非收藏品版本（除了老主顾）。

**Comment by NagaResst** [comment]
已更新  [下载地址](http://43.142.142.18/Paissa.zip)

**Comment by status102** [comment]
看到你14天才看到这个issue了（笑
总之，感谢更新，等会回去试下

**Comment by NagaResst** [comment]
一直没注意这还有个issue   hhhhhhhhhhhhhh @status102
