### ISSUE TITLE
挂代理时启动没有反应

### ISSUE THREAD

**Issue by Jock-SSH** [GHMesLing/Paissa#31]
不挂梯子的时候，可以正常使用，打开梯子之后，软件点击就没有反应了

**Comment by NagaResst** [comment]
windows上不能正确获取代理设置，导致网络异常，不能正确在线检索版本所以启动不了。这个事情我知道，但是我完全复现不了，我自己也用梯子一点事都没。你可以试试1.0.4，估计能启动，但是不能查询（然并卵）。

**Comment by NagaResst** [comment]
@Jock-SSH   试试这个 https://github.com/NagaResst/Paissa/releases/download/v1.0.4/Paissa-beta-v1.0.4-for-use-proxy.zip

**Comment by Jock-SSH** [comment]
感谢回复，我再研究下代理设置，谢谢
