### ISSUE TITLE
v1.0.4在Win11下无法正常运行

### ISSUE THREAD

**Issue by mnsosmk2** [GHMesLing/Paissa#32]
### 操作系统（如MacOS 10.15）
>
Windows 11 22H2 家庭版（22621.2428）

### 网络环境（移动，联通，电信，移动宽带，联通宽带，电信宽带，等等..）
>
电信，代理与非代理环境都尝试过。

### 问题描述（简要描述发生的问题）
>
直接运行与管理员模式运行都无法打开应用程序，进程内也没有找到paissa相关，兼容模式尝试了win7与win8也是无法运行。

**Comment by mnsosmk2** [comment]
补充：无额外安装杀软，已关闭防火墙与windows defender防护。兼容性疑难诊断中出现报错如下：
![image](https://github.com/NagaResst/Paissa/assets/144557135/c3e43cf8-f912-4406-a509-64835086a67e)

**Comment by mnsosmk2** [comment]
> @Jock-SSH 试试这个 https://github.com/NagaResst/Paissa/releases/download/v1.0.4/Paissa-beta-v1.0.4-for-use-proxy.zip

使用该版本所有网络环境可正常运行。代理软件为clash for windows v0.20.30，非代理环境是在直连的配置中操作的，release中直接下载的v1.0.4在开启clash中出现无法正常运行情况。

**Comment by NagaResst** [comment]
> > @Jock-SSH 试试这个 https://github.com/NagaResst/Paissa/releases/download/v1.0.4/Paissa-beta-v1.0.4-for-use-proxy.zip
> 
> 使用该版本所有网络环境可正常运行。代理软件为clash for windows v0.20.30，非代理环境是在直连的配置中操作的，release中直接下载的v1.0.4在开启clash中出现无法正常运行情况。

多谢反馈，启动没有反应主要问题还是在于版本检索更新的时候出现了网络问题。近期会找个可靠的在线源托管代码，到时候会发布新版本的主文件需要手动更新。
