### ISSUE TITLE
替换了marketable.py和item.Pdt 还是查询不了7.05的产品

### ISSUE THREAD

**Issue by hjtao889** [GHMesLing/Paissa#34]
rt

**Comment by hjtao889** [comment]
看日志输出 7.05的东西是写入完毕了 marketable.py和item.Pdt  我都能找到对应的物品id

**Comment by hjtao889** [comment]
Paissa.py中 重新下载替换数据包文件 我也删了

**Comment by NagaResst** [comment]
我还没推送7.05的数据包呢。下午回家了看一下，如果有新版本数据就推上来。

**Comment by hjtao889** [comment]
按照版本数据更新的方法自己生成新数据文件的

**Comment by NagaResst** [comment]
抱歉，我在更新器里写的算法有点问题，现在是版本不同就会拉取数据覆盖。所以，自己更新的数据文件会被就版本覆盖。
我在写新的流水线每周自动去更新数据版本。

**Comment by NagaResst** [comment]
已经更新完了，你试一下。

**Comment by hjtao889** [comment]
感谢 现在搜成本 好多了
